clear
load dataReducedFormatFA1P.mat

for lFile=1:length(dataC)
lFile
%[LevaLoglik(lFile),errLeva] = dhmm_logprob(dataC{lFile}.actions, LevapriorOpt, LevaTMOpt, LevaEMOpt);
[achuLoglik(lFile),errAchu] = dhmm_logprob(dataC{lFile}.behSeq, AchupriorOpt, AchuTMOpt, AchuEMOpt);%prob to observe sequence having generated by that model likelie of genera
[oldoLoglik(lFile),errOldo] = dhmm_logprob(dataC{lFile}.behSeq, OldopriorOpt, OldoTMOpt, OldoEMOpt);
end

for lFile=1:length(dataC)
lFile
    %    [LevaLoglik(lFile),errLeva] = hmmviterbi(dataC{lFile}.actions, LevaTMOpt, LevaEMOpt);
    achuViterbiSeq{lFile} = hmmviterbi(dataC{lFile}.behSeq, AchuTMOpt, AchuEMOpt);
    oldoViterbiSeq{lFile} = hmmviterbi(dataC{lFile}.behSeq, OldoTMOpt, OldoEMOpt);% sequence of hidden states. How many hidden states. try 3,4 5 and see if fit becomes better or not
    %seqLen(lFile) = length(dataC{lFile}.actions);
end


for ll=1:length(dataC)
ll
SUCCESS = XLSWRITE([filesToRead{ll} 'achuInternalStatesFAFA1P.xls'],filesToRead{ll},'A1')
SUCCESS = XLSWRITE([filesToRead{ll} 'achuInternalStatesFAFA1P.xls'],'6 internal states - achu model','A2')
SUCCESS = XLSWRITE([filesToRead{ll} 'achuInternalStatesFAFA1P.xls'],achuViterbiSeq{ll}','A3:A2000')

SUCCESS = XLSWRITE([filesToRead{ll} 'oldoInternalStatesFAFA1P.xls'],filesToRead{ll},'A1')
SUCCESS = XLSWRITE([filesToRead{ll} 'oldoInternalStatesFAFA1P.xls'],'6 internal states - oldo model','A2')
SUCCESS = XLSWRITE([filesToRead{ll} 'oldoInternalStatesFAFA1P.xls'],oldoViterbiSeq{ll}','A3:A2000')
end


[obsSeqAchu,intSeqAchu] =hmmgenerate(500,AchuTMOpt, AchuEMOpt);
[obsSeqOldo,intSeqOldo] =hmmgenerate(500,OldoTMOpt, OldoEMOpt);

SUCCESS = XLSWRITE('VirtualAchuelianSeqFAFA1P.xls',obsSeqAchu','A1:A2000')
SUCCESS = XLSWRITE('VirtualAchuelianSeqFAFA1P.xls',intSeqAchu','B1:B2000')

SUCCESS = XLSWRITE('VirtualOldowanSeqFAFA1P.xls',obsSeqOldo','A1:A2000')
SUCCESS = XLSWRITE('VirtualOldowanSeqFAFA1P.xls',intSeqOldo','B1:B2000')
